version: "3"
services:

  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    container_name: users
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - .:/app
      - /app/users/node_modules

    env_file:
      - ./users/.env

  tickets:
    build:
      dockerfile: Dockerfile
      context: ./tickets
    container_name: tickets
    ports:
      - "8002:8002"
    restart: always
    volumes:
      - .:/app
      - /app/tickets/node_modules

    env_file:
      - ./tickets/.env

  notifications:
    build:
      dockerfile: Dockerfile
      context: ./notifications
    container_name: notifications
    ports:
      - "8003:8003"
    restart: always
    volumes:
      - .:/app
      - /app/notifications/node_modules

    
    env_file:
      - ./notifications/.env
  otp:
    build:
      dockerfile: Dockerfile
      context: ./otp
    container_name: otp
    ports:
      - "8005:8005"
    restart: always
    volumes:
      - .:/app
      - /app/otp/node_modules

    
    env_file:
      - ./otp/.env

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - users
      - tickets
      - notifications
      - otp
    ports:
      - "80:80"
      