version: "3"
services:

  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    # image: toluwalasee/users
      
    container_name: users
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - ./users/:/app/users
      - /app/users/node_modules

  tickets:
    build:
      dockerfile: Dockerfile
      context: ./tickets
    # image: toluwalasee/tickets
    container_name: tickets
    ports:
      - "8002:8002"
    restart: always
    volumes:
      - ./tickets/:/app/tickets
      - /app/tickets/node_modules

  notifications:
    build:
      dockerfile: Dockerfile
      context: ./notifications
    # image: toluwalasee/notifications
    container_name: notifications
    ports:
      - "8003:8003"
    restart: always
    volumes:
      - ./notifications/:/app/notifications
      - /app/notifications/node_modules

  otp:
    build:
      dockerfile: Dockerfile
      context: ./otp
    container_name: otp
    ports:
      - "8005:8005"
    restart: always
    volumes:
      - ./otp/:/app/otp
      - /app/otp/node_modules

  payment:
    build:
      dockerfile: Dockerfile
      context: ./payment
    container_name: payment
    ports:
      - "8006:8006"
    restart: always
    volumes:
      - ./payment/:/app/payment
      - /app/payment/node_modules

    
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - users
      - tickets
      - notifications
      - otp
      - payment
    ports:
      - "8000:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      