version: "3"
services:

  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    container_name: users
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - .:/app
      - /app/users/node_modules

    env_file:
      - ./users/.env

  tickets:
    build:
      dockerfile: Dockerfile
      context: ./tickets
    container_name: tickets
    ports:
      - "8002:8002"
    restart: always
    volumes:
      - .:/app
      - /app/tickets/node_modules

    
    env_file:
      - ./tickets/.env

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - users
      - tickets
    ports:
      - "80:80"
      