version: "3"
services:

  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    image: toluwalasee/users

  tickets:
    build:
      dockerfile: Dockerfile
      context: ./tickets
    container_name: tickets
    image: toluwalasee/tickets

  notifications:
    build:
      dockerfile: Dockerfile
      context: ./notifications
    image: toluwalasee/notifications

  otp:
    build:
      dockerfile: Dockerfile
      context: ./otp
    image: toluwalasee/otp
  payment:
    build:
      dockerfile: Dockerfile
      context: ./payment
    image: toluwalasee/payment
  nginx-proxy:
  
    build:
      dockerfile: Dockerfile
      context: ./proxy
    image: toluwalasee/nginx-proxy
    depends_on:
      - users
      - tickets
      - notifications
      - otp
      - payment
      