apiVersion: skaffold/v4beta2
kind: Config

build:
# define where to find the code at build time and where to push the resulting image
  googleCloudBuild:
    projectId: saferoad-dev
  
  artifacts:
  - image: gcr.io/saferoad-dev/users
    context: users
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
  - image: gcr.io/saferoad-dev/tickets
    context: tickets
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
    docker:
        dockerfile: Dockerfile


# defines the Kubernetes manifests to deploy on each run
manifests:
  rawYaml:
  - ./infra/k8s/*
# deploy:
#   cloudrun:
#     projectid: saferoad-dev
#     region: us-central1

profiles:       
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
    artifacts:
    - image: gcr.io/saferoad-dev/users
      context: users
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      kaniko:
        cache: {}

        
  

