
name: Deploy to aws

on:
  pull_request:
    branches: [ "master","dev" ]

jobs:
  deploy_on_qa:

    runs-on: ubuntu-latest
    environment: JWT_KEY
    env:
  # Setting an environment variable with the value of a configuration variable
        JWT_KEY: ${{vars.JWT_KEY}}
        AUTH_EMAIL: ${{vars.AUTH_EMAIL}}
        AUTH_PASS: ${{vars.AUTH_PASS}}

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
      
    - name: Create User Env file
      working-directory: ./users
      run: |
        touch .env
        echo JWT_KEY= ${{vars.JWT_KEY}} >> .env
        echo AUTH_EMAIL= ${{vars.AUTH_EMAIL}} >> .env
        echo AUTH_PASS= ${{vars.AUTH_PASS}} >> .env
        echo PORT = 8001
        cat .env
        
    - name: Generate deployemnt package
      run: |
        zip -r deploy.zip . -x '*.git'

       
    - name: Deploy on Elastic beanstalk QA Env
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
        aws_secret_key: ${{secrets.AWS_ACCESS_SECRET}}
        application_name: saferoad-dev
        environment_name: Saferoaddev-env
        version_labe: "ver-${{ github.sha}}"
        region: eu-central-1
        deployment_package: deploy.zip
      
