# This is a basic workflow to help you get started with Actions

name: tests



# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    paths: "users/**"
env:
  # Setting an environment variable with the value of a configuration variable
  JWT_KEY: ${{ vars.JWT_KEY }}
  AUTH_EMAIL: ${{vars.AUTH_EMAIL}}
  AUTH_JWT: ${{vars.AUTH_PASS}}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: echo 'Hi ${{ env.JWT_KEY }}'
      - run: echo 'Hi ${{ env.AUTH_EMAIL }}'
      - run: echo 'Hi ${{ env.AUTH_JWT}}'
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run test for user service

        run: cd users && npm install && npm run test:ci

